In [1]:
import re
import itertools
from dataclasses import dataclass
from typing import List, Dict, Tuple

import pandas as pd
import torch
from transformers import pipeline

/Users/timbarvenov/Documents/uam/sem1/uczenie_glebokie_all/uczenie_glebokie/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
texts = [
    "OpenAI was founded in 2015 by Sam Altman in San Francisco. The company later moved its headquarters to other offices.",

    "Google was founded in 1998 by Larry Page and Sergey Brin at Stanford University in California. Sundar Pichai became CEO in 2015.",

    "The University of Oxford was established in 1096 in Oxford, England. It is one of the oldest universities in Europe.",

    "Tesla was founded in 2003 in California by Martin Eberhard and Marc Tarpenning. Elon Musk joined the company later.",

    "Microsoft was founded in 1975 by Bill Gates and Paul Allen in Albuquerque. The company is based in Redmond today.",

    "Marie Curie was born in 1867 in Warsaw, Poland. She worked at the University of Paris and won a Nobel Prize.",

    "Amazon was founded in 1994 by Jeff Bezos in Seattle. The company expanded globally after 2000.",

    "Apple was founded in 1976 by Steve Jobs and Steve Wozniak in Cupertino. Tim Cook became CEO in 2011."
]

In [3]:
ner = pipeline(
    task="ner",
    model="dslim/bert-base-NER",
    aggregation_strategy="simple",
    device='mps'
)

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use mps

In [4]:
sentence_split_re = re.compile(r"(?<=[.!?])\s+")

def split_sentences(text):
    sents = [s.strip() for s in sentence_split_re.split(text) if s.strip()]
    return sents

split_sentences(texts[0])

['OpenAI was founded in 2015 by Sam Altman in San Francisco.',
 'The company later moved its headquarters to other offices.']

In [5]:
year_re = re.compile(r"\b(1[0-9]{3}|20[0-2][0-9])\b")

def extract_dates(text):
    out = []
    for m in year_re.finditer(text):
        out.append({
            "text": m.group(0),
            "type": "DATE",
            "start": m.start(),
            "end": m.end(),
            "score": 1.0,
            "source": "regex"
        })
    return out


label_map = {
    "PER": "PERSON",
    "ORG": "ORG",
    "LOC": "LOCATION",
    "MISC": "MISC"
}

def ner_entities(text):
    ents = []
    for e in ner(text):
        t = label_map.get(e["entity_group"], e["entity_group"])
        ents.append({
            "text": e["word"],
            "type": t,
            "start": int(e["start"]),
            "end": int(e["end"]),
            "score": float(e["score"]),
            "source": "model"
        })

    ents.extend(extract_dates(text))

    ents = sorted(ents, key=lambda x: (x["start"], x["end"]))
    return ents

In [6]:
def show_entities(text: str, ents: List[Dict]):
    df = pd.DataFrame(ents)[["text","type","start","end","score","source"]]
    display(df)

ents0 = ner_entities(texts[0])
show_entities(texts[0], ents0)

            text      type  start  end     score source
0         OpenAI       ORG      0    6  0.987911  model
1           2015      DATE     22   26  1.000000  regex
2     Sam Altman    PERSON     30   40  0.993201  model
3  San Francisco  LOCATION     44   57  0.999368  model

In [7]:
def entities_in_sentence(sent, offset, all_ents):
    s0, s1 = offset, offset + len(sent)
    return [e for e in all_ents if e["start"] >= s0 and e["end"] <= s1]

def sentence_offsets(text):
    sents = []
    start = 0
    for m in sentence_split_re.finditer(text):
        end = m.start()
        sent = text[start:end].strip()
        if sent:
            true_start = text.find(sent, start, end)
            sents.append((sent, true_start))
        start = m.end()

    last = text[start:].strip()
    if last:
        true_start = text.find(last, start)
        sents.append((last, true_start))
    return sents

def entity_pairs_in_sentence(ents):
    return list(itertools.combinations(ents, 2))

def count_pairs_for_text(text):
    all_ents = ner_entities(text)
    sent_info = sentence_offsets(text)
    total_pairs = 0
    per_sent = []
    for sent, off in sent_info:
        ents = entities_in_sentence(sent, off, all_ents)
        pairs = entity_pairs_in_sentence(ents)
        per_sent.append((sent, len(ents), len(pairs)))
        total_pairs += len(pairs)
    return all_ents, per_sent, total_pairs

all_ents, per_sent, total_pairs = count_pairs_for_text(texts[0])
per_sent, total_pairs

([('OpenAI was founded in 2015 by Sam Altman in San Francisco.', 4, 6),
  ('The company later moved its headquarters to other offices.', 0, 0)],
 6)

In [8]:
def classify_relation(sent, e1, e2):
    s = sent.lower()
    t1, t2 = e1["type"], e2["type"]

    pair = {t1, t2}

    founded_kw = any(k in s for k in ["was founded", "founded in", "founded by", "established", "was established"]) 
    by_kw = " by " in s or "founded by" in s
    in_kw = " in " in s
    ceo_kw = " ceo" in s or "chief executive" in s
    works_kw = any(k in s for k in ["worked at", "works at", "joined", "employed", "at the"]) 

    if pair == {"ORG", "PERSON"} and founded_kw and by_kw:
        return "FOUNDED_BY"

    if pair == {"ORG", "DATE"} and founded_kw:
        return "FOUNDED_IN_YEAR"

    if pair == {"ORG", "LOCATION"} and ("based in" in s or (founded_kw and in_kw) or "headquarters" in s):
        return "LOCATED_IN"

    if pair == {"ORG", "PERSON"} and ceo_kw:
        return "CEO_OF"

    if pair == {"ORG", "PERSON"} and works_kw:
        return "WORKS_AT"

    return "NO_RELATION"

In [10]:
def run_ie(text: str):
    ents = ner_entities(text)
    sent_info = sentence_offsets(text)

    rel_rows = []
    pair_stats = []

    for sent, off in sent_info:
        sent_ents = entities_in_sentence(sent, off, ents)
        pairs = entity_pairs_in_sentence(sent_ents)
        pair_stats.append({
            "sentence": sent,
            "num_entities": len(sent_ents),
            "num_pairs": len(pairs)
        })
        for e1, e2 in pairs:
            rel = classify_relation(sent, e1, e2)
            rel_rows.append({"sentence": sent,
                             "e1": e1["text"], "e1_type": e1["type"],
                             "e2": e2["text"], "e2_type": e2["type"],
                             "relation": rel})

    return ents, pd.DataFrame(pair_stats), pd.DataFrame(rel_rows)

results = []
for i, text in enumerate(texts):
    ents, pair_stats_df, rel_df = run_ie(text)
    results.append((ents, pair_stats_df, rel_df))
    
    print(f"\n=== TEXT {i} ===")
    print(text)
    print("\nEntities:")
    display(pd.DataFrame(ents)[["text","type","start","end","source"]])
    print("\nPairs per sentence:")
    display(pair_stats_df)
    print("\nRelations (candidates):")
    display(rel_df)

=== TEXT 0 ===
OpenAI was founded in 2015 by Sam Altman in San Francisco. The company later moved its headquarters to other offices.

Entities:

            text      type  start  end source
0         OpenAI       ORG      0    6  model
1           2015      DATE     22   26  regex
2     Sam Altman    PERSON     30   40  model
3  San Francisco  LOCATION     44   57  model

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  OpenAI was founded in 2015 by Sam Altman in Sa...             4          6
1  The company later moved its headquarters to ot...             0          0

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,OpenAI was founded in 2015 by Sam Altman in Sa...,OpenAI,ORG,2015,DATE,FOUNDED_IN_YEAR
1,OpenAI was founded in 2015 by Sam Altman in Sa...,OpenAI,ORG,Sam Altman,PERSON,FOUNDED_BY
2,OpenAI was founded in 2015 by Sam Altman in Sa...,OpenAI,ORG,San Francisco,LOCATION,LOCATED_IN
3,OpenAI was founded in 2015 by Sam Altman in Sa...,2015,DATE,Sam Altman,PERSON,NO_RELATION
4,OpenAI was founded in 2015 by Sam Altman in Sa...,2015,DATE,San Francisco,LOCATION,NO_RELATION
5,OpenAI was founded in 2015 by Sam Altman in Sa...,Sam Altman,PERSON,San Francisco,LOCATION,NO_RELATION

=== TEXT 1 ===
Google was founded in 1998 by Larry Page and Sergey Brin at Stanford University in California. Sundar Pichai became CEO in 2015.

Entities:

                  text      type  start  end source
0               Google       ORG      0    6  model
1                 1998      DATE     22   26  regex
2           Larry Page    PERSON     30   40  model
3          Sergey Brin    PERSON     45   56  model
4  Stanford University       ORG     60   79  model
5           California  LOCATION     83   93  model
6        Sundar Pichai    PERSON     95  108  model
7                 2015      DATE    123  127  regex

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  Google was founded in 1998 by Larry Page and S...             6         15
1                  Sundar Pichai became CEO in 2015.             2          1

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,Google was founded in 1998 by Larry Page and S...,Google,ORG,1998,DATE,FOUNDED_IN_YEAR
1,Google was founded in 1998 by Larry Page and S...,Google,ORG,Larry Page,PERSON,FOUNDED_BY
2,Google was founded in 1998 by Larry Page and S...,Google,ORG,Sergey Brin,PERSON,FOUNDED_BY
3,Google was founded in 1998 by Larry Page and S...,Google,ORG,Stanford University,ORG,NO_RELATION
4,Google was founded in 1998 by Larry Page and S...,Google,ORG,California,LOCATION,LOCATED_IN
5,Google was founded in 1998 by Larry Page and S...,1998,DATE,Larry Page,PERSON,NO_RELATION
6,Google was founded in 1998 by Larry Page and S...,1998,DATE,Sergey Brin,PERSON,NO_RELATION
7,Google was founded in 1998 by Larry Page and S...,1998,DATE,Stanford University,ORG,FOUNDED_IN_YEAR
8,Google was founded in 1998 by Larry Page and S...,1998,DATE,California,LOCATION,NO_RELATION
9,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,Sergey Brin,PERSON,NO_RELATION
10,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,Stanford University,ORG,FOUNDED_BY
11,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,California,LOCATION,NO_RELATION
12,Google was founded in 1998 by Larry Page and S...,Sergey Brin,PERSON,Stanford University,ORG,FOUNDED_BY
13,Google was founded in 1998 by Larry Page and S...,Sergey Brin,PERSON,California,LOCATION,NO_RELATION
14,Google was founded in 1998 by Larry Page and S...,Stanford University,ORG,California,LOCATION,LOCATED_IN
15,Sundar Pichai became CEO in 2015.,Sundar Pichai,PERSON,2015,DATE,NO_RELATION

=== TEXT 2 ===
The University of Oxford was established in 1096 in Oxford, England. It is one of the oldest universities in Europe.

Entities:

                   text      type  start  end source
0  University of Oxford       ORG      4   24  model
1                  1096      DATE     44   48  regex
2                Oxford  LOCATION     52   58  model
3               England  LOCATION     60   67  model
4                Europe  LOCATION    109  115  model

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  The University of Oxford was established in 10...             4          6
1    It is one of the oldest universities in Europe.             1          0

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,The University of Oxford was established in 10...,University of Oxford,ORG,1096,DATE,FOUNDED_IN_YEAR
1,The University of Oxford was established in 10...,University of Oxford,ORG,Oxford,LOCATION,LOCATED_IN
2,The University of Oxford was established in 10...,University of Oxford,ORG,England,LOCATION,LOCATED_IN
3,The University of Oxford was established in 10...,1096,DATE,Oxford,LOCATION,NO_RELATION
4,The University of Oxford was established in 10...,1096,DATE,England,LOCATION,NO_RELATION
5,The University of Oxford was established in 10...,Oxford,LOCATION,England,LOCATION,NO_RELATION

=== TEXT 3 ===
Tesla was founded in 2003 in California by Martin Eberhard and Marc Tarpenning. Elon Musk joined the company later.

Entities:

              text      type  start  end source
0            Tesla       ORG      0    5  model
1             2003      DATE     21   25  regex
2       California  LOCATION     29   39  model
3  Martin Eberhard    PERSON     43   58  model
4  Marc Tarpenning    PERSON     63   78  model
5               El       ORG     80   82  model
6          ##on Mu    PERSON     82   87  model
7             ##sk       ORG     87   89  model

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  Tesla was founded in 2003 in California by Mar...             5         10
1                Elon Musk joined the company later.             3          3

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,Tesla was founded in 2003 in California by Mar...,Tesla,ORG,2003,DATE,FOUNDED_IN_YEAR
1,Tesla was founded in 2003 in California by Mar...,Tesla,ORG,California,LOCATION,LOCATED_IN
2,Tesla was founded in 2003 in California by Mar...,Tesla,ORG,Martin Eberhard,PERSON,FOUNDED_BY
3,Tesla was founded in 2003 in California by Mar...,Tesla,ORG,Marc Tarpenning,PERSON,FOUNDED_BY
4,Tesla was founded in 2003 in California by Mar...,2003,DATE,California,LOCATION,NO_RELATION
5,Tesla was founded in 2003 in California by Mar...,2003,DATE,Martin Eberhard,PERSON,NO_RELATION
6,Tesla was founded in 2003 in California by Mar...,2003,DATE,Marc Tarpenning,PERSON,NO_RELATION
7,Tesla was founded in 2003 in California by Mar...,California,LOCATION,Martin Eberhard,PERSON,NO_RELATION
8,Tesla was founded in 2003 in California by Mar...,California,LOCATION,Marc Tarpenning,PERSON,NO_RELATION
9,Tesla was founded in 2003 in California by Mar...,Martin Eberhard,PERSON,Marc Tarpenning,PERSON,NO_RELATION
10,Elon Musk joined the company later.,El,ORG,##on Mu,PERSON,WORKS_AT
11,Elon Musk joined the company later.,El,ORG,##sk,ORG,NO_RELATION
12,Elon Musk joined the company later.,##on Mu,PERSON,##sk,ORG,WORKS_AT

=== TEXT 4 ===
Microsoft was founded in 1975 by Bill Gates and Paul Allen in Albuquerque. The company is based in Redmond today.

Entities:

          text      type  start  end source
0    Microsoft       ORG      0    9  model
1         1975      DATE     25   29  regex
2   Bill Gates    PERSON     33   43  model
3   Paul Allen    PERSON     48   58  model
4  Albuquerque  LOCATION     62   73  model
5      Redmond  LOCATION     99  106  model

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  Microsoft was founded in 1975 by Bill Gates an...             5         10
1             The company is based in Redmond today.             1          0

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,Microsoft was founded in 1975 by Bill Gates an...,Microsoft,ORG,1975,DATE,FOUNDED_IN_YEAR
1,Microsoft was founded in 1975 by Bill Gates an...,Microsoft,ORG,Bill Gates,PERSON,FOUNDED_BY
2,Microsoft was founded in 1975 by Bill Gates an...,Microsoft,ORG,Paul Allen,PERSON,FOUNDED_BY
3,Microsoft was founded in 1975 by Bill Gates an...,Microsoft,ORG,Albuquerque,LOCATION,LOCATED_IN
4,Microsoft was founded in 1975 by Bill Gates an...,1975,DATE,Bill Gates,PERSON,NO_RELATION
5,Microsoft was founded in 1975 by Bill Gates an...,1975,DATE,Paul Allen,PERSON,NO_RELATION
6,Microsoft was founded in 1975 by Bill Gates an...,1975,DATE,Albuquerque,LOCATION,NO_RELATION
7,Microsoft was founded in 1975 by Bill Gates an...,Bill Gates,PERSON,Paul Allen,PERSON,NO_RELATION
8,Microsoft was founded in 1975 by Bill Gates an...,Bill Gates,PERSON,Albuquerque,LOCATION,NO_RELATION
9,Microsoft was founded in 1975 by Bill Gates an...,Paul Allen,PERSON,Albuquerque,LOCATION,NO_RELATION

=== TEXT 5 ===
Marie Curie was born in 1867 in Warsaw, Poland. She worked at the University of Paris and won a Nobel Prize.

Entities:

                  text      type  start  end source
0          Marie Curie    PERSON      0   11  model
1                 1867      DATE     24   28  regex
2               Warsaw  LOCATION     32   38  model
3               Poland  LOCATION     40   46  model
4  University of Paris       ORG     66   85  model
5          Nobel Prize      MISC     96  107  model

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0    Marie Curie was born in 1867 in Warsaw, Poland.             4          6
1  She worked at the University of Paris and won ...             2          1

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,"Marie Curie was born in 1867 in Warsaw, Poland.",Marie Curie,PERSON,1867,DATE,NO_RELATION
1,"Marie Curie was born in 1867 in Warsaw, Poland.",Marie Curie,PERSON,Warsaw,LOCATION,NO_RELATION
2,"Marie Curie was born in 1867 in Warsaw, Poland.",Marie Curie,PERSON,Poland,LOCATION,NO_RELATION
3,"Marie Curie was born in 1867 in Warsaw, Poland.",1867,DATE,Warsaw,LOCATION,NO_RELATION
4,"Marie Curie was born in 1867 in Warsaw, Poland.",1867,DATE,Poland,LOCATION,NO_RELATION
5,"Marie Curie was born in 1867 in Warsaw, Poland.",Warsaw,LOCATION,Poland,LOCATION,NO_RELATION
6,She worked at the University of Paris and won ...,University of Paris,ORG,Nobel Prize,MISC,NO_RELATION

=== TEXT 6 ===
Amazon was founded in 1994 by Jeff Bezos in Seattle. The company expanded globally after 2000.

Entities:

         text      type  start  end source
0      Amazon       ORG      0    6  model
1        1994      DATE     22   26  regex
2  Jeff Bezos    PERSON     30   40  model
3     Seattle  LOCATION     44   51  model
4        2000      DATE     89   93  regex

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  Amazon was founded in 1994 by Jeff Bezos in Se...             4          6
1          The company expanded globally after 2000.             1          0

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,Amazon was founded in 1994 by Jeff Bezos in Se...,Amazon,ORG,1994,DATE,FOUNDED_IN_YEAR
1,Amazon was founded in 1994 by Jeff Bezos in Se...,Amazon,ORG,Jeff Bezos,PERSON,FOUNDED_BY
2,Amazon was founded in 1994 by Jeff Bezos in Se...,Amazon,ORG,Seattle,LOCATION,LOCATED_IN
3,Amazon was founded in 1994 by Jeff Bezos in Se...,1994,DATE,Jeff Bezos,PERSON,NO_RELATION
4,Amazon was founded in 1994 by Jeff Bezos in Se...,1994,DATE,Seattle,LOCATION,NO_RELATION
5,Amazon was founded in 1994 by Jeff Bezos in Se...,Jeff Bezos,PERSON,Seattle,LOCATION,NO_RELATION

=== TEXT 7 ===
Apple was founded in 1976 by Steve Jobs and Steve Wozniak in Cupertino. Tim Cook became CEO in 2011.

Entities:

            text      type  start  end source
0          Apple       ORG      0    5  model
1           1976      DATE     21   25  regex
2     Steve Jobs    PERSON     29   39  model
3  Steve Wozniak    PERSON     44   57  model
4      Cupertino  LOCATION     61   70  model
5       Tim Cook    PERSON     72   80  model
6           2011      DATE     95   99  regex

Pairs per sentence:

                                            sentence  num_entities  num_pairs
0  Apple was founded in 1976 by Steve Jobs and St...             5         10
1                       Tim Cook became CEO in 2011.             2          1

Relations (candidates):

,sentence,e1,e1_type,e2,e2_type,relation
0,Apple was founded in 1976 by Steve Jobs and St...,Apple,ORG,1976,DATE,FOUNDED_IN_YEAR
1,Apple was founded in 1976 by Steve Jobs and St...,Apple,ORG,Steve Jobs,PERSON,FOUNDED_BY
2,Apple was founded in 1976 by Steve Jobs and St...,Apple,ORG,Steve Wozniak,PERSON,FOUNDED_BY
3,Apple was founded in 1976 by Steve Jobs and St...,Apple,ORG,Cupertino,LOCATION,LOCATED_IN
4,Apple was founded in 1976 by Steve Jobs and St...,1976,DATE,Steve Jobs,PERSON,NO_RELATION
5,Apple was founded in 1976 by Steve Jobs and St...,1976,DATE,Steve Wozniak,PERSON,NO_RELATION
6,Apple was founded in 1976 by Steve Jobs and St...,1976,DATE,Cupertino,LOCATION,NO_RELATION
7,Apple was founded in 1976 by Steve Jobs and St...,Steve Jobs,PERSON,Steve Wozniak,PERSON,NO_RELATION
8,Apple was founded in 1976 by Steve Jobs and St...,Steve Jobs,PERSON,Cupertino,LOCATION,NO_RELATION
9,Apple was founded in 1976 by Steve Jobs and St...,Steve Wozniak,PERSON,Cupertino,LOCATION,NO_RELATION
10,Tim Cook became CEO in 2011.,Tim Cook,PERSON,2011,DATE,NO_RELATION

In [11]:
chosen = 1
ents, pair_stats_df, rel_df = results[chosen]

print("TEXT:")
print(texts[chosen])

print("\nEntities:")
display(pd.DataFrame(ents)[["text","type","source"]])

print("\nPairs per sentence (count):")
display(pair_stats_df)
print("Total pairs:", int(pair_stats_df["num_pairs"].sum()))

print("\nAll relation candidates:")
display(rel_df.sort_values(["relation","e1","e2"]))

TEXT:
Google was founded in 1998 by Larry Page and Sergey Brin at Stanford University in California. Sundar Pichai became CEO in 2015.

Entities:

                  text      type source
0               Google       ORG  model
1                 1998      DATE  regex
2           Larry Page    PERSON  model
3          Sergey Brin    PERSON  model
4  Stanford University       ORG  model
5           California  LOCATION  model
6        Sundar Pichai    PERSON  model
7                 2015      DATE  regex

Pairs per sentence (count):

                                            sentence  num_entities  num_pairs
0  Google was founded in 1998 by Larry Page and S...             6         15
1                  Sundar Pichai became CEO in 2015.             2          1

Total pairs: 16

All relation candidates:

,sentence,e1,e1_type,e2,e2_type,relation
1,Google was founded in 1998 by Larry Page and S...,Google,ORG,Larry Page,PERSON,FOUNDED_BY
2,Google was founded in 1998 by Larry Page and S...,Google,ORG,Sergey Brin,PERSON,FOUNDED_BY
10,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,Stanford University,ORG,FOUNDED_BY
12,Google was founded in 1998 by Larry Page and S...,Sergey Brin,PERSON,Stanford University,ORG,FOUNDED_BY
7,Google was founded in 1998 by Larry Page and S...,1998,DATE,Stanford University,ORG,FOUNDED_IN_YEAR
0,Google was founded in 1998 by Larry Page and S...,Google,ORG,1998,DATE,FOUNDED_IN_YEAR
4,Google was founded in 1998 by Larry Page and S...,Google,ORG,California,LOCATION,LOCATED_IN
14,Google was founded in 1998 by Larry Page and S...,Stanford University,ORG,California,LOCATION,LOCATED_IN
8,Google was founded in 1998 by Larry Page and S...,1998,DATE,California,LOCATION,NO_RELATION
5,Google was founded in 1998 by Larry Page and S...,1998,DATE,Larry Page,PERSON,NO_RELATION
6,Google was founded in 1998 by Larry Page and S...,1998,DATE,Sergey Brin,PERSON,NO_RELATION
3,Google was founded in 1998 by Larry Page and S...,Google,ORG,Stanford University,ORG,NO_RELATION
11,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,California,LOCATION,NO_RELATION
9,Google was founded in 1998 by Larry Page and S...,Larry Page,PERSON,Sergey Brin,PERSON,NO_RELATION
13,Google was founded in 1998 by Larry Page and S...,Sergey Brin,PERSON,California,LOCATION,NO_RELATION
15,Sundar Pichai became CEO in 2015.,Sundar Pichai,PERSON,2015,DATE,NO_RELATION

### Wnioski

Zdanie: "Google was founded in 1998 by Larry Page and Sergey Brin at Stanford University in California. Sundar Pichai became CEO in 2015."

**Poprawne relacje**:
- (Google, Larry Page) → FOUNDED_BY
- (Google, Sergey Brin) → FOUNDED_BY
- (Google, 1998) → FOUNDED_IN_YEAR

2) **Błędne/wątpliwe**:
- (Google, California) → LOCATED_IN (zależy od interpretacji, to raczej ma być FOUNDED_IN)
- (Larry Page, Stanford University) → FOUNDED_BY: Błędne, przyczyna: prosty `if` wykrył słowa „founded … by” oraz parę (PERSON, ORG)
- (Sergey Brin, Stanford University) → FOUNDED_BY: Błędne, przyczyna taka sama
- (1998, Stanford University) → FOUNDED_IN_YEAR: Błędne, zadziałało tak samo jak dla `(Google, 1998) → FOUNDED_IN_YEAR`